### ISSUE TITLE
New Download UI

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-monorepo#29]
### Description

_See https://redmine.apidb.org/issues/12938_

The new download UI will make use of a WDK record and question. The page will be comprised of two parts: a custom question form at the top (`GetAllFileRecords`); and a live table view below, based on the question form configuration. Files can be downloaded by selecting rows and clicking a "Download" button.

---

### Implementation details

- Use the question `GetAllFileRecords`
- Reuse the search form, from which we can construct an Answer value
- Reuse ResultTableSummaryView
- Allow downloading individual files by clicking a link in the table row
- Allow selecting multiple rows and performing a bulk download action. **This depends on a service form endpoint to generate a tarball. Maybe it could be a reporter?**

---

### TODOs from UI-Infra discussion on April 11, 2023

- [x] Title: Download Data Files
- [x] fix filterParam verbiage: (shows ‘genes’ instead fo Files)
- [x] filterParam: fix size container
- [ ] filterParam values: organisms: make a tree? (will require adding ability to override filter ui)
- [x] show Data Type filter first
- [ ] ~default filter on current release~
- [x] Results table: add columns to ontology
- [x] Column defaults: remove file name and path, leave: file ID (File Name) , Organism, Release #(not Build), Data type and File format.
- [x] sorting: release and file Id: fileName
- [x] column ID make: link to path

**Comment by dmfalke** [comment]
### UX Apr 19, 2023 TODOs (UI)

- [ ] Support for query params to initialize page
