### ISSUE TITLE
Correlation: Get visualization on page and show the bipartite network

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-monorepo#512]
See [here](https://veupathdb.atlassian.net/wiki/spaces/WG/pages/12976129/Correlation+app) for more details.

Tasks

- [x] Create the formal bipartite network component #517 
- [x] add empty correlation endpoint to data service https://github.com/VEuPathDB/EdaDataService/pull/322
- [x] add the Correlation compute plugin #522 
- [x] add the bipartite network viz #522 
- [x] use fake data to generate a bipartite network when the viz is visited #522 
- [x] make sure thumbnail works #522

**Comment by asizemore** [comment]
All done! Closing

**Comment by asizemore** [comment]
Nothing to QA
