### ISSUE TITLE
Parent issue: Add assay1 vs assay2 correlation plugin

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-monorepo#661]
This issue tracks the backend and frontend tasks for adding a new flavor of correlation plugin. This flavor will take one type of assay (for example, pathway abundance) and correlate it with another chosen assay (for example, taxa abundance). The resulting viz will be a bipartite network, just like we have for the current correlation plugin.

Backend:

- [ ] https://github.com/VEuPathDB/microbiomeComputations/issues/61
- [ ] https://github.com/VEuPathDB/service-eda-compute/issues/76
- [ ] https://github.com/VEuPathDB/EdaDataService/issues/333

Frontend:
todo

**Comment by asizemore** [comment]
wow this is done!
