### ISSUE TITLE
Parent issue: polishing updates for bipartite network

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-monorepo#667]
More details in this [confluence doc](https://veupathdb.atlassian.net/wiki/spaces/WG/pages/12976129/Correlation+app)

The viz looks good but there are a few ways it could look even better ;)  These issues together get the viz production-ready.

To Do:

- [x] Choose final high/low color for edges. Requires discussion. Update 01/03/23 - These two colors do well for color blindness. They do okay for grayscale. So I'm removing this as an immediate requirement for release
- [x] #669 
- [x] #668 
- [x] https://github.com/VEuPathDB/web-monorepo/issues/731 https://github.com/VEuPathDB/web-monorepo/pull/732
- [x] #747
- [x] #728 https://github.com/VEuPathDB/web-monorepo/pull/741
- [x] #727 https://github.com/VEuPathDB/web-monorepo/pull/741
- [x] #716 
- [x] Add viz icon https://github.com/VEuPathDB/web-monorepo/pull/676
- [ ] Rename bpnet component to `BipartiteNetworkPlot`, and the component type to `BipartiteNetwork`. See https://github.com/VEuPathDB/web-monorepo/pull/765#issuecomment-1894126534. Also double check that each component has "Plot" in its name as part of this cleanup. -> moving to https://github.com/VEuPathDB/web-monorepo/issues/815

**Comment by asizemore** [comment]
When QA-ing this ticket, please check to see if the correlation apps work for DIY data!

**Comment by asizemore** [comment]
The last checkbox is tech debt so i moved it to its own issue. Closing
